server:
  error:
    whitelabel:
      enabled: false
  port: 5000

spring:
  application:
    name: dou-k8s-helloworld
  profiles:
    active: local
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id:
            client-name: Cognito
            provider: cognito
            scope: openid
            redirect-uri-template: "http://localhost:5000/logged"
            redirect-uri: "http://localhost:5000/logged"
            authorization-grant-type: authorization_code
        provider:
          cognito:
            authorization-uri: https://hello-dou-oauth3.auth.${aws.region}.amazoncognito.com/oauth2/authorize
            token-uri: https://hello-dou-oauth3.auth.${aws.region}.amazoncognito.com/oauth2/token
            user-info-uri: https://hello-dou-oauth3.auth.${aws.region}.amazoncognito.com/oauth2/userInfo
            jwk-set-uri: https://cognito-idp.${aws.region}.amazonaws.com/${aws.region}/.well-known/jwks.json
            user-name-attribute: cognito:nickname
---
aws:
  cognito:
    poolId:
    clientAppId:
    clientAppSecret:
  functionName:
  region:
  accessKeyId:
  secretKey: